language: python

install:
- pip install pelican ghp-import markdown

# this would build the blog:
script:
 - pelican content/

deploy:
- provider: script
  script: ci/to-ghp.sh
  skip_cleanup: true
  on:
    branch: master

env:
  global:
    # Change if required
    - GH_REPO=nixos.unstable.krebsco.de
    - secure: s83zyRJ1WvPNi+1y98Ds/03qKVvzDzkyHorrQE/80Bay/CoCXVHL5dlvSz8HB8TE70ojkBJM8imb+h9ToEXn0joa/pUko72zytRCWXTGkYT/Xn/0RGjI/KY+cdbGhFjw9TOVy+cO3eS19NzwtBJG1nf1roowrsMyg7Wvceafpd0aY+J/dRq/TrW528ooqeivslsnY3USOsuZRnJPTxp2aqXQXi4zNKZ04CZtIMG6AH8DWH/OBwc03qp9Xw2ifERVf4k5IVXK+ezKJlgP4ZeOneNAgzoc0b7qQIggehl5HtK6ROg4Pkm3Y3ksyGdz8NQNTWINkISU7HUNKejUbfr2FUsAjq2dn1OhTceIvmF45anPkBJO1/4Qhz3DzvrwpTGmZUiA0VFdubT90WApWHaPrKX0KM5JU+JVapPPHTS3k6LW0wEIu79/27c1HXaj1M+gdgvVnODN3pSHFKDp+OctMiaoYgM0CsJPqKCWMyEw89lmFBdxSgtjRtAduoFt6VHxO9m0E7g2c5gYYtKfsYHgIWvfaAnEIHDj9Q8k5d2dJAa5bLyvkr5uwaW7yo9VgEnnIYezD0/ksuwTJ/+My2gj7qf7BFrjBZXfDhPVrdc0dWi1aeaX2km1hs0GqtRkTMDg6nw3+oMJogLCN/ZX0JGijPwX2VGJKKgxHxkdQn+ynTg=
